### ISSUE TITLE
[Refactor] 신고하기 대상자 변경

### ISSUE THREAD

**Issue by dlrjs2360** [HowBaChu/Backend#100]
## ✅ TASK

- [x] 신고 대상자를 댓글로 변경합니다.
- [ ] 댓글은 일정 기준을 넘어서면 가려집니다.
- [ ] 내가 신고한 댓글은 표시되지 않습니다.

## 📝 TODO
- [ ] 신고 엔티티의 Target을 댓글로 바꿉니다.
- [ ] 멤버와 댓글 엔티티에 신고 카운트 컬럼을 추가합니다.
- [ ] 댓글이 신고될 때마다 댓글의 신고 카운트를 1씩 늘리고 일정 기준을 넘기면 댓글이 삭제됩니다.
- [ ] 댓글 신고가 누적되어 댓글이 삭제될 때마다 댓글을 작성한 주인의 신고 카운트를 1씩 늘리고 일정 기준을 넘기면 계정이 정지됩니다.

## 🤔 HELP
- [ ] 신고자에게는 신고한 댓글이 가려질 수 있는 구조를 고민중입니다.
