### ISSUE TITLE
[Refactor] 전체적인 코드 리팩토링

### ISSUE THREAD

**Issue by dlrjs2360** [HowBaChu/Backend#97]
## ✅ TODO
- [x] 도메인 로직 중 디미터 법칙을 위반한 부분을 변경합니다.
- [x] 객체가 가진 데이터는 객체 내에서 사용하도록 변경합니다.
- [x] 코드 형식을 일정한 형식으로 통일합니다.
- [x] 구글 컨벤션에 따라 정렬합니다.
- [x] 외부에 노출할 데이터와 그렇지 않은 데이터를 구분하여 접근제어자를 변경합니다.
